### ISSUE TITLE
Using version() method

### ISSUE THREAD

**Issue by ryanfoote** [mmikkel/Detect-Craft#3]
Hi!

Calling `version()` only seems to return a boolean value. For example, `craft.detect.version('Safari')` returns "1" on iOS 11 Safari. Via Mobile Detect's [demo page](http://demo.mobiledetect.net/), `version('Safari')` returns "11.0".

Is this an issue that can be cleared up by updating the Mobile Detect library in the plugin to the current version?

**Comment by mmikkel** [comment]
Hi @ryanfoote – I just published [Detect 1.0.2](https://github.com/mmikkel/Detect-Craft/releases/tag/v.1.0.2), which has the latest version for Mobile_Detect. I haven't been able to test it on iOS, though. If you can test it for me, that'd be a big help :)

**Comment by ryanfoote** [comment]
That didn't seem to be the issue. I'm still getting "1" returned when `craft.detect.version('Safari')` is called.
